services:
  postgres:
    image: postgres
    volumes:
      - ./src/main/resources/database_scripts/create.sql:/docker-entrypoint-initdb.d/01-create.sql
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"