services:
  postgres:
    image: postgres
    volumes:
      - ./src/main/resources/initialize_database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
